// Função para dividir a string Base64 e decodificar partes dela
function base64DecodeLarge(str) {
    const chunkSize = 1024 * 1024; // Tamanho do chunk (ajuste conforme necessário)
    let decoded = '';

    for (let i = 0; i < str.length; i += chunkSize) {
        let chunk = str.slice(i, i + chunkSize);
        decoded += atob(chunk);
    }

    try {
        return decodeURIComponent(escape(decoded));  // Isso pode ser desnecessário dependendo do tipo de dado
    } catch (e) {
        console.error("Erro ao decodificar a string: ", e);
        return decoded;
    }
}

// Substitua esta string pelo seu código BASE64
const base64String = "eyJldmVudCI6eyJfaWQiOiI2Nzk4ZTdmZTQ0MDEwZjI5MWE5Y2Y1ZWUiLCJtYXhfeHAiOjEwNjI1MDAwLCJtYXhfbXVsdGlwbGllciI6MTAwMDAsIm1heF9sZXZlbCI6MjAsInByb2dyZXNzaW9uX2V2ZW50X3R5cGUiOiJkZWZhdWx0IiwiZW5kX2RhdGUiOiIyMDI1LTAxLTMwVDE1OjAwOjAwLjAwMFoiLCJsYXN0X3VwZGF0ZWQiOjE3MzgwNzQxMTEwMDEsImRlc2NyaXB0aW9uIjp7ImVuIjoiWzI44oCTMzAgSmFuXSBSZWQgRW52ZWxvcGUgUnVzaCIsImNuIjoiWzI44oCTMzAgSmFuXSBSZWQgRW52ZWxvcGUgUnVzaCJ9LCJ0aXRsZSI6eyJlbiI6IlJlZCBFbnZlbG9wZSBSdXNoIiwiY24iOiJSZWQgRW52ZWxvcGUgUnVzaCJ9fSwicmV3YXJkcyI6W3siaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyMTEiLCJpdGVtX2lkIjpudWxsLCJhbW91bnQiOjEwMDAwMDAwMCwiY3VycmVuY3kiOiJSU1QiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjEsInR5cGUiOiJtb25leSIsInRpdGxlIjp7ImVuIjoiTW9uZXkgVGl0bGUiLCJjbiI6Ik1vbmV5IFRpdGxlIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTW9uZXkgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNb25leSBSZXdhcmQgRGVzY3JpcHRpb24ifX0seyJpZCI6IjY3OThlODAwYTI2YzM3YzMwZjg2MjIxNiIsIml0ZW1faWQiOiI2NGVjOTE0YzIyYzc1MTEwYjliMDk1NjIiLCJhbW91bnQiOjEsImN1cnJlbmN5IjoiIiwidHRsX3RpbWUiOjAsInJlcXVpcmVkX2xldmVsIjoyLCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2NGVjOTE0YzIyYzc1MTEwYjliMDk1NjIiLCJjcmVhdGVkX2J5X3RpdGxlIjp7ImxpbmsiOiIiLCJ0ZXh0IjoiIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiSXQgaXMgbm90IGEgY29weSBvZiBNZXJnZWRnZS4gTm8uIEFic29sdXRlbHkgbm90LiBCcmFuZC1uZXcgbWluZXIuIEV2ZW4gYmluZGluZyB2YWx1ZSBpcyBkaWZmZXJlbnQhIFRvdGFsbHkgbmV3IG1pbmVyLiIsImNuIjoiSXQgaXMgbm90IGEgY29weSBvZiBNZXJnZWRnZS4gTm8uIEFic29sdXRlbHkgbm90LiBCcmFuZC1uZXcgbWluZXIuIEV2ZW4gYmluZGluZyB2YWx1ZSBpcyBkaWZmZXJlbnQhIFRvdGFsbHkgbmV3IG1pbmVyLiIsImVzIjoiSXQgaXMgbm90IGEgY29weSBvZiBNZXJnZWRnZS4gTm8uIEFic29sdXRlbHkgbm90LiBCcmFuZC1uZXcgbWluZXIuIEV2ZW4gYmluZGluZyB2YWx1ZSBpcyBkaWZmZXJlbnQhIFRvdGFsbHkgbmV3IG1pbmVyLiIsInB0IjoiSXQgaXMgbm90IGEgY29weSBvZiBNZXJnZWRnZS4gTm8uIEFic29sdXRlbHkgbm90LiBCcmFuZC1uZXcgbWluZXIuIEV2ZW4gYmluZGluZyB2YWx1ZSBpcyBkaWZmZXJlbnQhIFRvdGFsbHkgbmV3IG1pbmVyLiJ9LCJmaWxlbmFtZSI6ImJlcmdlZGdlIiwiaXNfY2FuX2JlX3NvbGRfb25fbXAiOmZhbHNlLCJsZXZlbCI6MywibmFtZSI6eyJlbiI6IkJlcmdlZGdlIiwiY24iOiJCZXJnZWRnZSIsImVzIjoiQmVyZ2VkZ2UiLCJwdCI6IkJlcmdlZGdlIn0sInBvd2VyIjo2NTQxNSwidHlwZSI6Im1lcmdlIiwid2lkdGgiOjIsImJvbnVzIjo0MSwiaXNfaW5fc2V0IjpmYWxzZX19LHsiaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyMWEiLCJpdGVtX2lkIjoiNjRlYzkxNGMyMmM3NTExMGI5YjA5NTYyIiwiYW1vdW50IjoxLCJjdXJyZW5jeSI6IiIsInR0bF90aW1lIjowLCJyZXF1aXJlZF9sZXZlbCI6MywidHlwZSI6Im1pbmVyIiwidGl0bGUiOnsiZW4iOiJNaW5lciBSZXdhcmQiLCJjbiI6Ik1pbmVyIFJld2FyZCJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiIsImNuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIn0sIml0ZW0iOnsiX2lkIjoiNjRlYzkxNGMyMmM3NTExMGI5YjA5NTYyIiwiY3JlYXRlZF9ieV90aXRsZSI6eyJsaW5rIjoiIiwidGV4dCI6IiJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6Ikl0IGlzIG5vdCBhIGNvcHkgb2YgTWVyZ2VkZ2UuIE5vLiBBYnNvbHV0ZWx5IG5vdC4gQnJhbmQtbmV3IG1pbmVyLiBFdmVuIGJpbmRpbmcgdmFsdWUgaXMgZGlmZmVyZW50ISBUb3RhbGx5IG5ldyBtaW5lci4iLCJjbiI6Ikl0IGlzIG5vdCBhIGNvcHkgb2YgTWVyZ2VkZ2UuIE5vLiBBYnNvbHV0ZWx5IG5vdC4gQnJhbmQtbmV3IG1pbmVyLiBFdmVuIGJpbmRpbmcgdmFsdWUgaXMgZGlmZmVyZW50ISBUb3RhbGx5IG5ldyBtaW5lci4iLCJlcyI6Ikl0IGlzIG5vdCBhIGNvcHkgb2YgTWVyZ2VkZ2UuIE5vLiBBYnNvbHV0ZWx5IG5vdC4gQnJhbmQtbmV3IG1pbmVyLiBFdmVuIGJpbmRpbmcgdmFsdWUgaXMgZGlmZmVyZW50ISBUb3RhbGx5IG5ldyBtaW5lci4iLCJwdCI6Ikl0IGlzIG5vdCBhIGNvcHkgb2YgTWVyZ2VkZ2UuIE5vLiBBYnNvbHV0ZWx5IG5vdC4gQnJhbmQtbmV3IG1pbmVyLiBFdmVuIGJpbmRpbmcgdmFsdWUgaXMgZGlmZmVyZW50ISBUb3RhbGx5IG5ldyBtaW5lci4ifSwiZmlsZW5hbWUiOiJiZXJnZWRnZSIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjpmYWxzZSwibGV2ZWwiOjMsIm5hbWUiOnsiZW4iOiJCZXJnZWRnZSIsImNuIjoiQmVyZ2VkZ2UiLCJlcyI6IkJlcmdlZGdlIiwicHQiOiJCZXJnZWRnZSJ9LCJwb3dlciI6NjU0MTUsInR5cGUiOiJtZXJnZSIsIndpZHRoIjoyLCJib251cyI6NDEsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDBhMjZjMzdjMzBmODYyMjFlIiwiaXRlbV9pZCI6IjY0ZWM5MTRjMjJjNzUxMTBiOWIwOTU2YyIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjQsInR5cGUiOiJtaW5lciIsInRpdGxlIjp7ImVuIjoiTWluZXIgUmV3YXJkIiwiY24iOiJNaW5lciBSZXdhcmQifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24iLCJjbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiJ9LCJpdGVtIjp7Il9pZCI6IjY0ZWM5MTRjMjJjNzUxMTBiOWIwOTU2YyIsImNyZWF0ZWRfYnlfdGl0bGUiOnsibGluayI6IiIsInRleHQiOiIifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJJdCBpcyBub3QgYSBjb3B5IG9mIE1lcmdlZGdlLiBOby4gQWJzb2x1dGVseSBub3QuIEJyYW5kLW5ldyBtaW5lci4gRXZlbiBiaW5kaW5nIHZhbHVlIGlzIGRpZmZlcmVudCEgVG90YWxseSBuZXcgbWluZXIuIiwiY24iOiJJdCBpcyBub3QgYSBjb3B5IG9mIE1lcmdlZGdlLiBOby4gQWJzb2x1dGVseSBub3QuIEJyYW5kLW5ldyBtaW5lci4gRXZlbiBiaW5kaW5nIHZhbHVlIGlzIGRpZmZlcmVudCEgVG90YWxseSBuZXcgbWluZXIuIiwiZXMiOiJJdCBpcyBub3QgYSBjb3B5IG9mIE1lcmdlZGdlLiBOby4gQWJzb2x1dGVseSBub3QuIEJyYW5kLW5ldyBtaW5lci4gRXZlbiBiaW5kaW5nIHZhbHVlIGlzIGRpZmZlcmVudCEgVG90YWxseSBuZXcgbWluZXIuIiwicHQiOiJJdCBpcyBub3QgYSBjb3B5IG9mIE1lcmdlZGdlLiBOby4gQWJzb2x1dGVseSBub3QuIEJyYW5kLW5ldyBtaW5lci4gRXZlbiBiaW5kaW5nIHZhbHVlIGlzIGRpZmZlcmVudCEgVG90YWxseSBuZXcgbWluZXIuIn0sImZpbGVuYW1lIjoiYmVyZ2VkZ2UiLCJpc19jYW5fYmVfc29sZF9vbl9tcCI6ZmFsc2UsImxldmVsIjo0LCJuYW1lIjp7ImVuIjoiQmVyZ2VkZ2UiLCJjbiI6IkJlcmdlZGdlIiwiZXMiOiJCZXJnZWRnZSIsInB0IjoiQmVyZ2VkZ2UifSwicG93ZXIiOjE3MTc4MCwidHlwZSI6Im1lcmdlIiwid2lkdGgiOjIsImJvbnVzIjo2NSwiaXNfaW5fc2V0IjpmYWxzZX19LHsiaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyMjIiLCJpdGVtX2lkIjoiNjRkNjJhN2Q2ZDcwMDgxNDg1NzVkZjdiIiwiYW1vdW50IjoxLCJjdXJyZW5jeSI6IiIsInR0bF90aW1lIjowLCJyZXF1aXJlZF9sZXZlbCI6NSwidHlwZSI6InJhY2siLCJ0aXRsZSI6eyJlbiI6IlJhY2sgVGl0bGUiLCJjbiI6IlJhY2sgVGl0bGUifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJSYWNrIFJld2FyZCBEZXNjcmlwdGlvbiIsImNuIjoiUmFjayBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJuYW1lIjp7ImVuIjoiTmVvbiBSYWNrIDgiLCJjbiI6Ik5lb24gUmFjayA4In0sImRlc2NyaXB0aW9uIjp7ImVuIjoiRW1icmFjZSB0aGUgdmlicmFudCBlbmVyZ3kgb2YgbmVvbiBsaWdodHMgd2l0aCB0aGlzIGZ1dHVyaXN0aWMgZmxhaXIgb2YgdGhlIE5lb24gUmFjay4iLCJjbiI6IkVtYnJhY2UgdGhlIHZpYnJhbnQgZW5lcmd5IG9mIG5lb24gbGlnaHRzIHdpdGggdGhpcyBmdXR1cmlzdGljIGZsYWlyIG9mIHRoZSBOZW9uIFJhY2suIn0sIl9pZCI6IjY0ZDYyYTdkNmQ3MDA4MTQ4NTc1ZGY3YiIsImNhcGFjaXR5Ijo4LCJpc19pbl9zZXQiOmZhbHNlfX0seyJpZCI6IjY3OThlODAwYTI2YzM3YzMwZjg2MjIyNiIsIml0ZW1faWQiOiI2M2NhOGY2MGE4ODJlN2EyNDk5NWNhOTIiLCJhbW91bnQiOjEsImN1cnJlbmN5IjoiIiwidHRsX3RpbWUiOjAsInJlcXVpcmVkX2xldmVsIjo2LCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2M2NhOGY2MGE4ODJlN2EyNDk5NWNhOTIiLCJwb3dlciI6Mjk2MzEwLCJ3aWR0aCI6MiwibmFtZSI6eyJlbiI6IlNoYW9saW4gVGVtcGxlIiwiY24iOiJTaGFvbGluIFRlbXBsZSIsImVzIjoiU2hhb2xpbiBUZW1wbGUiLCJwdCI6IlNoYW9saW4gVGVtcGxlIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiQSBwbGFjZSwgZnVsbCBvZiB0aHJlZS1sZWdnZWQgYnVsbGZyb2dzLCBzcGl0dGluZyBvdXQgYSBidW5jaCBvZiBjb2lucyBldmVyeSB0ZW4gbWludXRlcyEgVGFrZSBpdCwgYW5kIGJlIHJpY2ghIE9yLCBhdCBsZWFzdCwgeW914oCZbGwgb3duIGEgbG90IG9mIGNvb2wgZnJvZ3MuIFRoaXMgbWluZXIgaXMgb25lIG9mIHRoZSB3aW5uZXJzIG9mIHRoZSBNaW5lcnMgQXJ0IENvbnRlc3Q6IFJvbGxlcnZlcnNlLiBDcmVhdGVkIGJ5IFBldHRlckNoLiIsImNuIjoiQSBwbGFjZSwgZnVsbCBvZiB0aHJlZS1sZWdnZWQgYnVsbGZyb2dzLCBzcGl0dGluZyBvdXQgYSBidW5jaCBvZiBjb2lucyBldmVyeSB0ZW4gbWludXRlcyEgVGFrZSBpdCwgYW5kIGJlIHJpY2ghIE9yLCBhdCBsZWFzdCwgeW914oCZbGwgb3duIGEgbG90IG9mIGNvb2wgZnJvZ3MuIFRoaXMgbWluZXIgaXMgb25lIG9mIHRoZSB3aW5uZXJzIG9mIHRoZSBNaW5lcnMgQXJ0IENvbnRlc3Q6IFJvbGxlcnZlcnNlLiBDcmVhdGVkIGJ5IFBldHRlckNoLiIsImVzIjoiQSBwbGFjZSwgZnVsbCBvZiB0aHJlZS1sZWdnZWQgYnVsbGZyb2dzLCBzcGl0dGluZyBvdXQgYSBidW5jaCBvZiBjb2lucyBldmVyeSB0ZW4gbWludXRlcyEgVGFrZSBpdCwgYW5kIGJlIHJpY2ghIE9yLCBhdCBsZWFzdCwgeW914oCZbGwgb3duIGEgbG90IG9mIGNvb2wgZnJvZ3MuIFRoaXMgbWluZXIgaXMgb25lIG9mIHRoZSB3aW5uZXJzIG9mIHRoZSBNaW5lcnMgQXJ0IENvbnRlc3Q6IFJvbGxlcnZlcnNlLiBDcmVhdGVkIGJ5IFBldHRlckNoLiIsInB0IjoiQSBwbGFjZSwgZnVsbCBvZiB0aHJlZS1sZWdnZWQgYnVsbGZyb2dzLCBzcGl0dGluZyBvdXQgYSBidW5jaCBvZiBjb2lucyBldmVyeSB0ZW4gbWludXRlcyEgVGFrZSBpdCwgYW5kIGJlIHJpY2ghIE9yLCBhdCBsZWFzdCwgeW914oCZbGwgb3duIGEgbG90IG9mIGNvb2wgZnJvZ3MuIFRoaXMgbWluZXIgaXMgb25lIG9mIHRoZSB3aW5uZXJzIG9mIHRoZSBNaW5lcnMgQXJ0IENvbnRlc3Q6IFJvbGxlcnZlcnNlLiBDcmVhdGVkIGJ5IFBldHRlckNoLiJ9LCJjcmVhdGVkX2J5X3RpdGxlIjp7ImxpbmsiOiIiLCJ0ZXh0IjoiIn0sImxldmVsIjoxLCJ0eXBlIjoibWVyZ2UiLCJmaWxlbmFtZSI6InNoYW9saW5fdGVtcGxlIiwiaXNfY2FuX2JlX3NvbGRfb25fbXAiOmZhbHNlLCJib251cyI6NTUsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDBhMjZjMzdjMzBmODYyMjJjIiwiaXRlbV9pZCI6IjY1OTdiZDI1ZjM0MzNjODAyZjJmMTE0OSIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjcsInR5cGUiOiJtaW5lciIsInRpdGxlIjp7ImVuIjoiTWluZXIgUmV3YXJkIiwiY24iOiJNaW5lciBSZXdhcmQifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24iLCJjbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiJ9LCJpdGVtIjp7Il9pZCI6IjY1OTdiZDI1ZjM0MzNjODAyZjJmMTE0OSIsInBvd2VyIjozOTY3NTAsIndpZHRoIjoyLCJuYW1lIjp7ImVuIjoiU2hhZGV3b29kIFNvcmNlcmVyIiwiY24iOiJTaGFkZXdvb2QgU29yY2VyZXIiLCJlcyI6IlNoYWRld29vZCBTb3JjZXJlciIsInB0IjoiU2hhZGV3b29kIFNvcmNlcmVyIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiQ2hhbm5lbCB0aGUgYXJjYW5lIGluIGV2ZXJ5IG1pbmVkIGJ5dGUgd2l0aCBTaGFkZXdvb2QgU29yY2VyZXIuIFdpdG5lc3MgdGhlIGRhbmNlIG9mIHJlZCBtYWdpYyBpbiB0aGUgbWlzdCwgc2hhcGluZyBjcnlwdG8gZW5jaGFudG1lbnRzIGluIHRoZSBkYXJrbmVzcy4iLCJjbiI6IkNoYW5uZWwgdGhlIGFyY2FuZSBpbiBldmVyeSBtaW5lZCBieXRlIHdpdGggU2hhZGV3b29kIFNvcmNlcmVyLiBXaXRuZXNzIHRoZSBkYW5jZSBvZiByZWQgbWFnaWMgaW4gdGhlIG1pc3QsIHNoYXBpbmcgY3J5cHRvIGVuY2hhbnRtZW50cyBpbiB0aGUgZGFya25lc3MuIiwiZXMiOiJDaGFubmVsIHRoZSBhcmNhbmUgaW4gZXZlcnkgbWluZWQgYnl0ZSB3aXRoIFNoYWRld29vZCBTb3JjZXJlci4gV2l0bmVzcyB0aGUgZGFuY2Ugb2YgcmVkIG1hZ2ljIGluIHRoZSBtaXN0LCBzaGFwaW5nIGNyeXB0byBlbmNoYW50bWVudHMgaW4gdGhlIGRhcmtuZXNzLiIsInB0IjoiQ2hhbm5lbCB0aGUgYXJjYW5lIGluIGV2ZXJ5IG1pbmVkIGJ5dGUgd2l0aCBTaGFkZXdvb2QgU29yY2VyZXIuIFdpdG5lc3MgdGhlIGRhbmNlIG9mIHJlZCBtYWdpYyBpbiB0aGUgbWlzdCwgc2hhcGluZyBjcnlwdG8gZW5jaGFudG1lbnRzIGluIHRoZSBkYXJrbmVzcy4ifSwiY3JlYXRlZF9ieV90aXRsZSI6eyJsaW5rIjoiIiwidGV4dCI6IiJ9LCJsZXZlbCI6MCwidHlwZSI6ImJhc2ljIiwiZmlsZW5hbWUiOiJzaGFkZXdvb2Rfc29yY2VyZXIiLCJpc19jYW5fYmVfc29sZF9vbl9tcCI6ZmFsc2UsImJvbnVzIjowLCJpc19pbl9zZXQiOmZhbHNlfX0seyJpZCI6IjY3OThlODAwYTI2YzM3YzMwZjg2MjIzMCIsIml0ZW1faWQiOiI2M2NhOGY2NWE4ODJlN2EyNDk5NWNhZGQiLCJhbW91bnQiOjEsImN1cnJlbmN5IjoiIiwidHRsX3RpbWUiOjAsInJlcXVpcmVkX2xldmVsIjo4LCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2M2NhOGY2NWE4ODJlN2EyNDk5NWNhZGQiLCJwb3dlciI6ODkwMjk1LCJ3aWR0aCI6MiwibmFtZSI6eyJlbiI6IlR1IE5pYW4iLCJjbiI6IlR1IE5pYW4iLCJlcyI6IlR1IE5pYW4iLCJwdCI6IlR1IE5pYW4ifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJHb2xkZW4gYnVubnksIG1ha2UgbWUgZnVubnkhIERpZCB5b3Uga25vdyB0aGF0IHRob3NlIGhpZXJvZ2x5cGhzIGFjdHVhbGx5IG1lYW4gbm9vZGxlcz8gVGhpcyBtaW5lciBpcyBvbmUgb2YgdGhlIHdpbm5lcnMgb2YgdGhlIE1pbmVycyBBcnQgQ29udGVzdDogUm9sbGVydmVyc2UuIENyZWF0ZWQgYnkgcGFyeml2YWwuIiwiY24iOiJHb2xkZW4gYnVubnksIG1ha2UgbWUgZnVubnkhIERpZCB5b3Uga25vdyB0aGF0IHRob3NlIGhpZXJvZ2x5cGhzIGFjdHVhbGx5IG1lYW4gbm9vZGxlcz8gVGhpcyBtaW5lciBpcyBvbmUgb2YgdGhlIHdpbm5lcnMgb2YgdGhlIE1pbmVycyBBcnQgQ29udGVzdDogUm9sbGVydmVyc2UuIENyZWF0ZWQgYnkgcGFyeml2YWwuIiwiZXMiOiJHb2xkZW4gYnVubnksIG1ha2UgbWUgZnVubnkhIERpZCB5b3Uga25vdyB0aGF0IHRob3NlIGhpZXJvZ2x5cGhzIGFjdHVhbGx5IG1lYW4gbm9vZGxlcz8gVGhpcyBtaW5lciBpcyBvbmUgb2YgdGhlIHdpbm5lcnMgb2YgdGhlIE1pbmVycyBBcnQgQ29udGVzdDogUm9sbGVydmVyc2UuIENyZWF0ZWQgYnkgcGFyeml2YWwuIiwicHQiOiJHb2xkZW4gYnVubnksIG1ha2UgbWUgZnVubnkhIERpZCB5b3Uga25vdyB0aGF0IHRob3NlIGhpZXJvZ2x5cGhzIGFjdHVhbGx5IG1lYW4gbm9vZGxlcz8gVGhpcyBtaW5lciBpcyBvbmUgb2YgdGhlIHdpbm5lcnMgb2YgdGhlIE1pbmVycyBBcnQgQ29udGVzdDogUm9sbGVydmVyc2UuIENyZWF0ZWQgYnkgcGFyeml2YWwuIn0sImNyZWF0ZWRfYnlfdGl0bGUiOnsibGluayI6IiIsInRleHQiOiIifSwibGV2ZWwiOjEsInR5cGUiOiJtZXJnZSIsImZpbGVuYW1lIjoidHVfbmlhbiIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjpmYWxzZSwiYm9udXMiOjExOCwiaXNfaW5fc2V0IjpmYWxzZX19LHsiaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyMzQiLCJpdGVtX2lkIjpudWxsLCJhbW91bnQiOjUwMDAwMDAsImN1cnJlbmN5IjoiIiwidHRsX3RpbWUiOjYwNDgwMDAwMCwicmVxdWlyZWRfbGV2ZWwiOjksInR5cGUiOiJwb3dlciIsInRpdGxlIjp7ImVuIjoiUG93ZXIiLCJjbiI6IlBvd2VyIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiUG93ZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJQb3dlciBSZXdhcmQgRGVzY3JpcHRpb24ifX0seyJpZCI6IjY3OThlODAwYTI2YzM3YzMwZjg2MjIzOSIsIml0ZW1faWQiOiI2M2NhOGY2MWE4ODJlN2EyNDk5NWNhYTUiLCJhbW91bnQiOjEsImN1cnJlbmN5IjoiIiwidHRsX3RpbWUiOjAsInJlcXVpcmVkX2xldmVsIjoxMCwidHlwZSI6Im1pbmVyIiwidGl0bGUiOnsiZW4iOiJNaW5lciBSZXdhcmQiLCJjbiI6Ik1pbmVyIFJld2FyZCJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiIsImNuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIn0sIml0ZW0iOnsiX2lkIjoiNjNjYThmNjFhODgyZTdhMjQ5OTVjYWE1IiwicG93ZXIiOjc3Nzg0MCwid2lkdGgiOjIsIm5hbWUiOnsiZW4iOiJTaGFvbGluIFRlbXBsZSIsImNuIjoiU2hhb2xpbiBUZW1wbGUiLCJlcyI6IlNoYW9saW4gVGVtcGxlIiwicHQiOiJTaGFvbGluIFRlbXBsZSJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6IkEgcGxhY2UsIGZ1bGwgb2YgdGhyZWUtbGVnZ2VkIGJ1bGxmcm9ncywgc3BpdHRpbmcgb3V0IGEgYnVuY2ggb2YgY29pbnMgZXZlcnkgdGVuIG1pbnV0ZXMhIFRha2UgaXQsIGFuZCBiZSByaWNoISBPciwgYXQgbGVhc3QsIHlvdeKAmWxsIG93biBhIGxvdCBvZiBjb29sIGZyb2dzLiBUaGlzIG1pbmVyIGlzIG9uZSBvZiB0aGUgd2lubmVycyBvZiB0aGUgTWluZXJzIEFydCBDb250ZXN0OiBSb2xsZXJ2ZXJzZS4gQ3JlYXRlZCBieSBQZXR0ZXJDaC4iLCJjbiI6IkEgcGxhY2UsIGZ1bGwgb2YgdGhyZWUtbGVnZ2VkIGJ1bGxmcm9ncywgc3BpdHRpbmcgb3V0IGEgYnVuY2ggb2YgY29pbnMgZXZlcnkgdGVuIG1pbnV0ZXMhIFRha2UgaXQsIGFuZCBiZSByaWNoISBPciwgYXQgbGVhc3QsIHlvdeKAmWxsIG93biBhIGxvdCBvZiBjb29sIGZyb2dzLiBUaGlzIG1pbmVyIGlzIG9uZSBvZiB0aGUgd2lubmVycyBvZiB0aGUgTWluZXJzIEFydCBDb250ZXN0OiBSb2xsZXJ2ZXJzZS4gQ3JlYXRlZCBieSBQZXR0ZXJDaC4iLCJlcyI6IkEgcGxhY2UsIGZ1bGwgb2YgdGhyZWUtbGVnZ2VkIGJ1bGxmcm9ncywgc3BpdHRpbmcgb3V0IGEgYnVuY2ggb2YgY29pbnMgZXZlcnkgdGVuIG1pbnV0ZXMhIFRha2UgaXQsIGFuZCBiZSByaWNoISBPciwgYXQgbGVhc3QsIHlvdeKAmWxsIG93biBhIGxvdCBvZiBjb29sIGZyb2dzLiBUaGlzIG1pbmVyIGlzIG9uZSBvZiB0aGUgd2lubmVycyBvZiB0aGUgTWluZXJzIEFydCBDb250ZXN0OiBSb2xsZXJ2ZXJzZS4gQ3JlYXRlZCBieSBQZXR0ZXJDaC4iLCJwdCI6IkEgcGxhY2UsIGZ1bGwgb2YgdGhyZWUtbGVnZ2VkIGJ1bGxmcm9ncywgc3BpdHRpbmcgb3V0IGEgYnVuY2ggb2YgY29pbnMgZXZlcnkgdGVuIG1pbnV0ZXMhIFRha2UgaXQsIGFuZCBiZSByaWNoISBPciwgYXQgbGVhc3QsIHlvdeKAmWxsIG93biBhIGxvdCBvZiBjb29sIGZyb2dzLiBUaGlzIG1pbmVyIGlzIG9uZSBvZiB0aGUgd2lubmVycyBvZiB0aGUgTWluZXJzIEFydCBDb250ZXN0OiBSb2xsZXJ2ZXJzZS4gQ3JlYXRlZCBieSBQZXR0ZXJDaC4ifSwiY3JlYXRlZF9ieV90aXRsZSI6eyJsaW5rIjoiIiwidGV4dCI6IiJ9LCJsZXZlbCI6MiwidHlwZSI6Im1lcmdlIiwiZmlsZW5hbWUiOiJzaGFvbGluX3RlbXBsZSIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjpmYWxzZSwiYm9udXMiOjE2NiwiaXNfaW5fc2V0IjpmYWxzZX19LHsiaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyM2QiLCJpdGVtX2lkIjpudWxsLCJhbW91bnQiOjUwMDAwMDAwMCwiY3VycmVuY3kiOiJSU1QiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjExLCJ0eXBlIjoibW9uZXkiLCJ0aXRsZSI6eyJlbiI6Ik1vbmV5IFRpdGxlIiwiY24iOiJNb25leSBUaXRsZSJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6Ik1vbmV5IFJld2FyZCBEZXNjcmlwdGlvbiIsImNuIjoiTW9uZXkgUmV3YXJkIERlc2NyaXB0aW9uIn19LHsiaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyNDEiLCJpdGVtX2lkIjoiNjc5MGVlODZiOWY1ZjkzODI0YzU1Y2ZhIiwiYW1vdW50IjoxLCJjdXJyZW5jeSI6IiIsInR0bF90aW1lIjowLCJyZXF1aXJlZF9sZXZlbCI6MTIsInR5cGUiOiJtaW5lciIsInRpdGxlIjp7ImVuIjoiTWluZXIgUmV3YXJkIiwiY24iOiJNaW5lciBSZXdhcmQifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24iLCJjbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiJ9LCJpdGVtIjp7Il9pZCI6IjY3OTBlZTg2YjlmNWY5MzgyNGM1NWNmYSIsInBvd2VyIjoyNDAwMDAwLCJ3aWR0aCI6MiwibmFtZSI6eyJlbiI6IkdvbGRlbiBQYXRoIiwiY24iOiJHb2xkZW4gUGF0aCIsImVzIjoiR29sZGVuIFBhdGgiLCJwdCI6IkdvbGRlbiBQYXRoIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiQSByYWRpYW50IHRyYWlsIGxlYWRpbmcgc3RyYWlnaHQgdG8gZm9ydHVuZSwgd2hlcmUgZXZlcnkgc3RlcCBzaGluZXMgd2l0aCBvcHBvcnR1bml0eS4iLCJjbiI6IkEgcmFkaWFudCB0cmFpbCBsZWFkaW5nIHN0cmFpZ2h0IHRvIGZvcnR1bmUsIHdoZXJlIGV2ZXJ5IHN0ZXAgc2hpbmVzIHdpdGggb3Bwb3J0dW5pdHkuIiwiZXMiOiJBIHJhZGlhbnQgdHJhaWwgbGVhZGluZyBzdHJhaWdodCB0byBmb3J0dW5lLCB3aGVyZSBldmVyeSBzdGVwIHNoaW5lcyB3aXRoIG9wcG9ydHVuaXR5LiIsInB0IjoiQSByYWRpYW50IHRyYWlsIGxlYWRpbmcgc3RyYWlnaHQgdG8gZm9ydHVuZSwgd2hlcmUgZXZlcnkgc3RlcCBzaGluZXMgd2l0aCBvcHBvcnR1bml0eS4ifSwiY3JlYXRlZF9ieV90aXRsZSI6eyJsaW5rIjoiIiwidGV4dCI6IiJ9LCJsZXZlbCI6MCwidHlwZSI6ImJhc2ljIiwiZmlsZW5hbWUiOiJnb2xkZW5fcGF0aCIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjp0cnVlLCJib251cyI6NTAsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDBhMjZjMzdjMzBmODYyMjQ1IiwiaXRlbV9pZCI6IjY1NzBhMTk0M2M0NjExOTU3MzIzZTIzNiIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjEzLCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2NTcwYTE5NDNjNDYxMTk1NzMyM2UyMzYiLCJwb3dlciI6NDkwMDAwLCJ3aWR0aCI6MiwibmFtZSI6eyJlbiI6IkdvbGRlbkdpZnRDcmFmdCIsImNuIjoiR29sZGVuR2lmdENyYWZ0IiwiZXMiOiJHb2xkZW5HaWZ0Q3JhZnQiLCJwdCI6IkdvbGRlbkdpZnRDcmFmdCJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6IkdvbGRlbkdpZnRDcmFmdCwgaW4gdGhlIGJsb2NrY2hhaW4ncyBlbWJyYWNlLCBBIGdvbGRlbiBib3ggb2Ygam95LCBpdHMgdHJlYXN1cmVzIHRvIHRyYWNlLiBTaGltbWVyaW5nIGJyaWdodCBpbiB0aGUgY3J5cHRvIG5pZ2h0LCBBIG1pbmVyIG9mIGdvbGQsIGluIGEgZmVzdGl2ZSBsaWdodCIsImNuIjoiR29sZGVuR2lmdENyYWZ0LCBpbiB0aGUgYmxvY2tjaGFpbidzIGVtYnJhY2UsIEEgZ29sZGVuIGJveCBvZiBqb3ksIGl0cyB0cmVhc3VyZXMgdG8gdHJhY2UuIFNoaW1tZXJpbmcgYnJpZ2h0IGluIHRoZSBjcnlwdG8gbmlnaHQsIEEgbWluZXIgb2YgZ29sZCwgaW4gYSBmZXN0aXZlIGxpZ2h0IiwiZXMiOiJHb2xkZW5HaWZ0Q3JhZnQsIGluIHRoZSBibG9ja2NoYWluJ3MgZW1icmFjZSwgQSBnb2xkZW4gYm94IG9mIGpveSwgaXRzIHRyZWFzdXJlcyB0byB0cmFjZS4gU2hpbW1lcmluZyBicmlnaHQgaW4gdGhlIGNyeXB0byBuaWdodCwgQSBtaW5lciBvZiBnb2xkLCBpbiBhIGZlc3RpdmUgbGlnaHQiLCJwdCI6IkdvbGRlbkdpZnRDcmFmdCwgaW4gdGhlIGJsb2NrY2hhaW4ncyBlbWJyYWNlLCBBIGdvbGRlbiBib3ggb2Ygam95LCBpdHMgdHJlYXN1cmVzIHRvIHRyYWNlLiBTaGltbWVyaW5nIGJyaWdodCBpbiB0aGUgY3J5cHRvIG5pZ2h0LCBBIG1pbmVyIG9mIGdvbGQsIGluIGEgZmVzdGl2ZSBsaWdodCJ9LCJjcmVhdGVkX2J5X3RpdGxlIjp7ImxpbmsiOiIiLCJ0ZXh0IjoiIn0sImxldmVsIjowLCJ0eXBlIjoiYmFzaWMiLCJmaWxlbmFtZSI6ImdvbGRlbmdpZnRjcmFmdCIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjp0cnVlLCJib251cyI6NDUsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDBhMjZjMzdjMzBmODYyMjRiIiwiaXRlbV9pZCI6IjY2OGQyMmE5NWEyNTM3NWZjODAzMzMzYiIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjE0LCJ0eXBlIjoicmFjayIsInRpdGxlIjp7ImVuIjoiUmFjayBUaXRsZSIsImNuIjoiUmFjayBUaXRsZSJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6IlJhY2sgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJSYWNrIFJld2FyZCBEZXNjcmlwdGlvbiJ9LCJpdGVtIjp7Im5hbWUiOnsiZW4iOiJQbGFudCBSYWNrIDYiLCJjbiI6IlBsYW50IFJhY2sgNiJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6IkEgY29tcGFjdCBhbmQgZ3JlZW4gbWluaW5nIHNvbHV0aW9uLCB0aGlzIHJhY2sgYWNjb21tb2RhdGVzIDYgbWluZXJzIGFuZCBpcyBkZXNpZ25lZCB0byBpbnRlZ3JhdGUgc2VhbWxlc3NseSBpbnRvIGVudmlyb25tZW50YWxseS1jb25zY2lvdXMgbWluaW5nIHNldHVwcy4iLCJjbiI6IkEgY29tcGFjdCBhbmQgZ3JlZW4gbWluaW5nIHNvbHV0aW9uLCB0aGlzIHJhY2sgYWNjb21tb2RhdGVzIDYgbWluZXJzIGFuZCBpcyBkZXNpZ25lZCB0byBpbnRlZ3JhdGUgc2VhbWxlc3NseSBpbnRvIGVudmlyb25tZW50YWxseS1jb25zY2lvdXMgbWluaW5nIHNldHVwcy4ifSwiX2lkIjoiNjY4ZDIyYTk1YTI1Mzc1ZmM4MDMzMzNiIiwiY2FwYWNpdHkiOjYsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDBhMjZjMzdjMzBmODYyMjUwIiwiaXRlbV9pZCI6IjY1MGRjMjdjMzM0MGZiZDYxNGE5MTIyNCIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjE1LCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2NTBkYzI3YzMzNDBmYmQ2MTRhOTEyMjQiLCJwb3dlciI6MTc4MjI3MCwid2lkdGgiOjIsIm5hbWUiOnsiZW4iOiJCbG9vZHkgTWFyeSIsImNuIjoiQmxvb2R5IE1hcnkiLCJlcyI6IkJsb29keSBNYXJ5IiwicHQiOiJCbG9vZHkgTWFyeSJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6Ikdyb2FucyBvZiBwYWluIGFuZCBob3Jyb3Igb2YgZXZlcnlvbmUsIHdobyB3YXMgbGVmdCBiZWhpbmQgeW91IGluIHRoZSBsZWFkZXJib2FyZCwgYXJlIGZlZWRpbmcgdGhpcyBsYWR5IHdpdGggbWluaW5nIHBvd2VyISBObyBtZXJjeSAtIG9ubHkgcGFzc2lvbiBmb3IgbWluaW5nIGhlcmUuIiwiY24iOiJHcm9hbnMgb2YgcGFpbiBhbmQgaG9ycm9yIG9mIGV2ZXJ5b25lLCB3aG8gd2FzIGxlZnQgYmVoaW5kIHlvdSBpbiB0aGUgbGVhZGVyYm9hcmQsIGFyZSBmZWVkaW5nIHRoaXMgbGFkeSB3aXRoIG1pbmluZyBwb3dlciEgTm8gbWVyY3kgLSBvbmx5IHBhc3Npb24gZm9yIG1pbmluZyBoZXJlLiIsImVzIjoiR3JvYW5zIG9mIHBhaW4gYW5kIGhvcnJvciBvZiBldmVyeW9uZSwgd2hvIHdhcyBsZWZ0IGJlaGluZCB5b3UgaW4gdGhlIGxlYWRlcmJvYXJkLCBhcmUgZmVlZGluZyB0aGlzIGxhZHkgd2l0aCBtaW5pbmcgcG93ZXIhIE5vIG1lcmN5IC0gb25seSBwYXNzaW9uIGZvciBtaW5pbmcgaGVyZS4iLCJwdCI6Ikdyb2FucyBvZiBwYWluIGFuZCBob3Jyb3Igb2YgZXZlcnlvbmUsIHdobyB3YXMgbGVmdCBiZWhpbmQgeW91IGluIHRoZSBsZWFkZXJib2FyZCwgYXJlIGZlZWRpbmcgdGhpcyBsYWR5IHdpdGggbWluaW5nIHBvd2VyISBObyBtZXJjeSAtIG9ubHkgcGFzc2lvbiBmb3IgbWluaW5nIGhlcmUuIn0sImNyZWF0ZWRfYnlfdGl0bGUiOnsibGluayI6IiIsInRleHQiOiIifSwibGV2ZWwiOjQsInR5cGUiOiJtZXJnZSIsImZpbGVuYW1lIjoiYmxvb2R5X21hcnkiLCJpc19jYW5fYmVfc29sZF9vbl9tcCI6dHJ1ZSwiYm9udXMiOjI4NCwiaXNfaW5fc2V0IjpmYWxzZX19LHsiaWQiOiI2Nzk4ZTgwMGEyNmMzN2MzMGY4NjIyNTQiLCJpdGVtX2lkIjoiNjU3MGExYzkzYzQ2MTE5NTczMjNlMjhlIiwiYW1vdW50IjoxLCJjdXJyZW5jeSI6IiIsInR0bF90aW1lIjowLCJyZXF1aXJlZF9sZXZlbCI6MTYsInR5cGUiOiJtaW5lciIsInRpdGxlIjp7ImVuIjoiTWluZXIgUmV3YXJkIiwiY24iOiJNaW5lciBSZXdhcmQifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24iLCJjbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiJ9LCJpdGVtIjp7Il9pZCI6IjY1NzBhMWM5M2M0NjExOTU3MzIzZTI4ZSIsInBvd2VyIjoxNzA0MDAwLCJ3aWR0aCI6MiwibmFtZSI6eyJlbiI6IlJ1YnlHaWZ0Q3JhZnQiLCJjbiI6IlJ1YnlHaWZ0Q3JhZnQiLCJlcyI6IlJ1YnlHaWZ0Q3JhZnQiLCJwdCI6IlJ1YnlHaWZ0Q3JhZnQifSwiZGVzY3JpcHRpb24iOnsiZW4iOiJJbiB0aGUgY3JpbXNvbiBjcnlwdG8tZ2xvdywgYSBzdG9yeSB0byBiZSB0b2xkLCBSdWJ5R2lmdENyYWZ0LCBtaW5pbmcgdHJlYXN1cmVzIG9mIHJlZCBhbmQgYm9sZC4gV3JhcHBlZCBpbiBwYXNzaW9uLCBhIGZlc3RpdmUgY2hlZXIsIEluIHRoZSBydWJ5IGh1ZXMsIGNyeXB0by13b25kZXJzIGFwcGVhci4iLCJjbiI6IkluIHRoZSBjcmltc29uIGNyeXB0by1nbG93LCBhIHN0b3J5IHRvIGJlIHRvbGQsIFJ1YnlHaWZ0Q3JhZnQsIG1pbmluZyB0cmVhc3VyZXMgb2YgcmVkIGFuZCBib2xkLiBXcmFwcGVkIGluIHBhc3Npb24sIGEgZmVzdGl2ZSBjaGVlciwgSW4gdGhlIHJ1YnkgaHVlcywgY3J5cHRvLXdvbmRlcnMgYXBwZWFyLiIsImVzIjoiSW4gdGhlIGNyaW1zb24gY3J5cHRvLWdsb3csIGEgc3RvcnkgdG8gYmUgdG9sZCwgUnVieUdpZnRDcmFmdCwgbWluaW5nIHRyZWFzdXJlcyBvZiByZWQgYW5kIGJvbGQuIFdyYXBwZWQgaW4gcGFzc2lvbiwgYSBmZXN0aXZlIGNoZWVyLCBJbiB0aGUgcnVieSBodWVzLCBjcnlwdG8td29uZGVycyBhcHBlYXIuIiwicHQiOiJJbiB0aGUgY3JpbXNvbiBjcnlwdG8tZ2xvdywgYSBzdG9yeSB0byBiZSB0b2xkLCBSdWJ5R2lmdENyYWZ0LCBtaW5pbmcgdHJlYXN1cmVzIG9mIHJlZCBhbmQgYm9sZC4gV3JhcHBlZCBpbiBwYXNzaW9uLCBhIGZlc3RpdmUgY2hlZXIsIEluIHRoZSBydWJ5IGh1ZXMsIGNyeXB0by13b25kZXJzIGFwcGVhci4ifSwiY3JlYXRlZF9ieV90aXRsZSI6eyJsaW5rIjoiIiwidGV4dCI6IiJ9LCJsZXZlbCI6MCwidHlwZSI6ImJhc2ljIiwiZmlsZW5hbWUiOiJydWJ5Z2lmdGNyYWZ0IiwiaXNfY2FuX2JlX3NvbGRfb25fbXAiOnRydWUsImJvbnVzIjo1MDAsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDBhMjZjMzdjMzBmODYyMjU4IiwiaXRlbV9pZCI6IjY0YTZmOTBkNTE1MDk5NzUyNDExZDkzMiIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjE3LCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2NGE2ZjkwZDUxNTA5OTc1MjQxMWQ5MzIiLCJwb3dlciI6MTI1MDg2NSwid2lkdGgiOjIsIm5hbWUiOnsiZW4iOiJLbmlnaHQgQnVzIiwiY24iOiJLbmlnaHQgQnVzIiwiZXMiOiJLbmlnaHQgQnVzIiwicHQiOiJLbmlnaHQgQnVzIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiWW91IGRpZCBleHBlY3QgYSBIYXJyeSBQb3R0ZXIgdmliZSBpbiB0aGUgRW5nbGlzaCBidXMsIHJpZ2h0LCB0cmF2ZWxlcj8gVGhpcyBtaWdodHkgc2F2ZXIgd2lsbCBwaWNrIHlvdSB1cCB3aGVuZXZlciB5b3UgYXJlIGFuZCB0YWtlIHlvdSBvbiBhIHJvYWQsIGZpbGxpbmcgeW91ciBwb2NrZXRzIHdpdGggY29pbnMhIEZhc3RlbiB0aGUgc2VhdGJlbHQsIHdl4oCZcmUgcmFpc2luZyB0aGUgc3BlZWQhIiwiY24iOiJZb3UgZGlkIGV4cGVjdCBhIEhhcnJ5IFBvdHRlciB2aWJlIGluIHRoZSBFbmdsaXNoIGJ1cywgcmlnaHQsIHRyYXZlbGVyPyBUaGlzIG1pZ2h0eSBzYXZlciB3aWxsIHBpY2sgeW91IHVwIHdoZW5ldmVyIHlvdSBhcmUgYW5kIHRha2UgeW91IG9uIGEgcm9hZCwgZmlsbGluZyB5b3VyIHBvY2tldHMgd2l0aCBjb2lucyEgRmFzdGVuIHRoZSBzZWF0YmVsdCwgd2XigJlyZSByYWlzaW5nIHRoZSBzcGVlZCEiLCJlcyI6IllvdSBkaWQgZXhwZWN0IGEgSGFycnkgUG90dGVyIHZpYmUgaW4gdGhlIEVuZ2xpc2ggYnVzLCByaWdodCwgdHJhdmVsZXI/IFRoaXMgbWlnaHR5IHNhdmVyIHdpbGwgcGljayB5b3UgdXAgd2hlbmV2ZXIgeW91IGFyZSBhbmQgdGFrZSB5b3Ugb24gYSByb2FkLCBmaWxsaW5nIHlvdXIgcG9ja2V0cyB3aXRoIGNvaW5zISBGYXN0ZW4gdGhlIHNlYXRiZWx0LCB3ZeKAmXJlIHJhaXNpbmcgdGhlIHNwZWVkISIsInB0IjoiWW91IGRpZCBleHBlY3QgYSBIYXJyeSBQb3R0ZXIgdmliZSBpbiB0aGUgRW5nbGlzaCBidXMsIHJpZ2h0LCB0cmF2ZWxlcj8gVGhpcyBtaWdodHkgc2F2ZXIgd2lsbCBwaWNrIHlvdSB1cCB3aGVuZXZlciB5b3UgYXJlIGFuZCB0YWtlIHlvdSBvbiBhIHJvYWQsIGZpbGxpbmcgeW91ciBwb2NrZXRzIHdpdGggY29pbnMhIEZhc3RlbiB0aGUgc2VhdGJlbHQsIHdl4oCZcmUgcmFpc2luZyB0aGUgc3BlZWQhIn0sImNyZWF0ZWRfYnlfdGl0bGUiOnsibGluayI6IiIsInRleHQiOiIifSwibGV2ZWwiOjIsInR5cGUiOiJtZXJnZSIsImZpbGVuYW1lIjoia25pZ2h0X2J1cyIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjp0cnVlLCJib251cyI6MTk2LCJpc19pbl9zZXQiOmZhbHNlfX0seyJpZCI6IjY3OThlODAxYTI2YzM3YzMwZjg2MjI1YyIsIml0ZW1faWQiOiI2NTcwYTE5NDNjNDYxMTk1NzMyM2UyMzkiLCJhbW91bnQiOjEsImN1cnJlbmN5IjoiIiwidHRsX3RpbWUiOjAsInJlcXVpcmVkX2xldmVsIjoxOCwidHlwZSI6Im1pbmVyIiwidGl0bGUiOnsiZW4iOiJNaW5lciBSZXdhcmQiLCJjbiI6Ik1pbmVyIFJld2FyZCJ9LCJkZXNjcmlwdGlvbiI6eyJlbiI6Ik1pbmVyIFJld2FyZCBEZXNjcmlwdGlvbiIsImNuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIn0sIml0ZW0iOnsiX2lkIjoiNjU3MGExOTQzYzQ2MTE5NTczMjNlMjM5IiwicG93ZXIiOjEyODYyNTAsIndpZHRoIjoyLCJuYW1lIjp7ImVuIjoiR29sZGVuR2lmdENyYWZ0IiwiY24iOiJHb2xkZW5HaWZ0Q3JhZnQiLCJlcyI6IkdvbGRlbkdpZnRDcmFmdCIsInB0IjoiR29sZGVuR2lmdENyYWZ0In0sImRlc2NyaXB0aW9uIjp7ImVuIjoiR29sZGVuR2lmdENyYWZ0LCBpbiB0aGUgYmxvY2tjaGFpbidzIGVtYnJhY2UsIEEgZ29sZGVuIGJveCBvZiBqb3ksIGl0cyB0cmVhc3VyZXMgdG8gdHJhY2UuIFNoaW1tZXJpbmcgYnJpZ2h0IGluIHRoZSBjcnlwdG8gbmlnaHQsIEEgbWluZXIgb2YgZ29sZCwgaW4gYSBmZXN0aXZlIGxpZ2h0IiwiY24iOiJHb2xkZW5HaWZ0Q3JhZnQsIGluIHRoZSBibG9ja2NoYWluJ3MgZW1icmFjZSwgQSBnb2xkZW4gYm94IG9mIGpveSwgaXRzIHRyZWFzdXJlcyB0byB0cmFjZS4gU2hpbW1lcmluZyBicmlnaHQgaW4gdGhlIGNyeXB0byBuaWdodCwgQSBtaW5lciBvZiBnb2xkLCBpbiBhIGZlc3RpdmUgbGlnaHQiLCJlcyI6IkdvbGRlbkdpZnRDcmFmdCwgaW4gdGhlIGJsb2NrY2hhaW4ncyBlbWJyYWNlLCBBIGdvbGRlbiBib3ggb2Ygam95LCBpdHMgdHJlYXN1cmVzIHRvIHRyYWNlLiBTaGltbWVyaW5nIGJyaWdodCBpbiB0aGUgY3J5cHRvIG5pZ2h0LCBBIG1pbmVyIG9mIGdvbGQsIGluIGEgZmVzdGl2ZSBsaWdodCIsInB0IjoiR29sZGVuR2lmdENyYWZ0LCBpbiB0aGUgYmxvY2tjaGFpbidzIGVtYnJhY2UsIEEgZ29sZGVuIGJveCBvZiBqb3ksIGl0cyB0cmVhc3VyZXMgdG8gdHJhY2UuIFNoaW1tZXJpbmcgYnJpZ2h0IGluIHRoZSBjcnlwdG8gbmlnaHQsIEEgbWluZXIgb2YgZ29sZCwgaW4gYSBmZXN0aXZlIGxpZ2h0In0sImNyZWF0ZWRfYnlfdGl0bGUiOnsibGluayI6IiIsInRleHQiOiIifSwibGV2ZWwiOjEsInR5cGUiOiJtZXJnZSIsImZpbGVuYW1lIjoiZ29sZGVuZ2lmdGNyYWZ0IiwiaXNfY2FuX2JlX3NvbGRfb25fbXAiOnRydWUsImJvbnVzIjoxMDgsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDFhMjZjMzdjMzBmODYyMjYyIiwiaXRlbV9pZCI6IjY1YmQyYThmNDNkY2FkOGY2ZDExOGI1ZCIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjE5LCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2NWJkMmE4ZjQzZGNhZDhmNmQxMThiNWQiLCJwb3dlciI6NDUyMDI1MCwid2lkdGgiOjIsIm5hbWUiOnsiZW4iOiJGdWxsIE1vb24gRHJhZ29uIiwiY24iOiJGdWxsIE1vb24gRHJhZ29uIiwiZXMiOiJGdWxsIE1vb24gRHJhZ29uIiwicHQiOiJGdWxsIE1vb24gRHJhZ29uIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWFnaWNhbCBNaW5lciBlbnZlbG9wZWQgaW4gdGhlIGdsb3cgb2YgdGhlIGJyaWdodGVzdCBtb29ubGl0IG5pZ2h0LiBJdHMgb3duZXIgcG9zc2Vzc2VzIHRoZSBwb3dlciBvZiBhbmNpZW50IGRyYWdvbnMgYW5kIHRoZSBwcm90ZWN0aW9uIG9mIHRoZSBmdWxsIG1vb24ncyBsaWdodC4gQnkgRGVhbiBXYWx0ZXIiLCJjbiI6Ik1hZ2ljYWwgTWluZXIgZW52ZWxvcGVkIGluIHRoZSBnbG93IG9mIHRoZSBicmlnaHRlc3QgbW9vbmxpdCBuaWdodC4gSXRzIG93bmVyIHBvc3Nlc3NlcyB0aGUgcG93ZXIgb2YgYW5jaWVudCBkcmFnb25zIGFuZCB0aGUgcHJvdGVjdGlvbiBvZiB0aGUgZnVsbCBtb29uJ3MgbGlnaHQuIEJ5IERlYW4gV2FsdGVyIiwiZXMiOiJNYWdpY2FsIE1pbmVyIGVudmVsb3BlZCBpbiB0aGUgZ2xvdyBvZiB0aGUgYnJpZ2h0ZXN0IG1vb25saXQgbmlnaHQuIEl0cyBvd25lciBwb3NzZXNzZXMgdGhlIHBvd2VyIG9mIGFuY2llbnQgZHJhZ29ucyBhbmQgdGhlIHByb3RlY3Rpb24gb2YgdGhlIGZ1bGwgbW9vbidzIGxpZ2h0LiBCeSBEZWFuIFdhbHRlciIsInB0IjoiTWFnaWNhbCBNaW5lciBlbnZlbG9wZWQgaW4gdGhlIGdsb3cgb2YgdGhlIGJyaWdodGVzdCBtb29ubGl0IG5pZ2h0LiBJdHMgb3duZXIgcG9zc2Vzc2VzIHRoZSBwb3dlciBvZiBhbmNpZW50IGRyYWdvbnMgYW5kIHRoZSBwcm90ZWN0aW9uIG9mIHRoZSBmdWxsIG1vb24ncyBsaWdodC4gQnkgRGVhbiBXYWx0ZXIifSwiY3JlYXRlZF9ieV90aXRsZSI6eyJsaW5rIjoiIiwidGV4dCI6IiJ9LCJsZXZlbCI6MSwidHlwZSI6Im1lcmdlIiwiZmlsZW5hbWUiOiJmdWxsX21vb25fZHJhZ29uIiwiaXNfY2FuX2JlX3NvbGRfb25fbXAiOnRydWUsImJvbnVzIjoyNDAsImlzX2luX3NldCI6ZmFsc2V9fSx7ImlkIjoiNjc5OGU4MDFhMjZjMzdjMzBmODYyMjY2IiwiaXRlbV9pZCI6IjY3OThjYjI0NDQwMTBmMjkxYTljNjNlZCIsImFtb3VudCI6MSwiY3VycmVuY3kiOiIiLCJ0dGxfdGltZSI6MCwicmVxdWlyZWRfbGV2ZWwiOjIwLCJ0eXBlIjoibWluZXIiLCJ0aXRsZSI6eyJlbiI6Ik1pbmVyIFJld2FyZCIsImNuIjoiTWluZXIgUmV3YXJkIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiTWluZXIgUmV3YXJkIERlc2NyaXB0aW9uIiwiY24iOiJNaW5lciBSZXdhcmQgRGVzY3JpcHRpb24ifSwiaXRlbSI6eyJfaWQiOiI2Nzk4Y2IyNDQ0MDEwZjI5MWE5YzYzZWQiLCJwb3dlciI6ODk1MDAwMCwid2lkdGgiOjIsIm5hbWUiOnsiZW4iOiJXZWFsdGggR2VuZXJhdG9yIiwiY24iOiJXZWFsdGggR2VuZXJhdG9yIiwiZXMiOiJXZWFsdGggR2VuZXJhdG9yIiwicHQiOiJXZWFsdGggR2VuZXJhdG9yIn0sImRlc2NyaXB0aW9uIjp7ImVuIjoiSW5zcGlyZWQgYnkgdGhlIHNwaXJpdCBvZiBnaXZpbmcsIHRoaXMgbWluZXIgcG93ZXJzIHRocm91Z2ggYmxvY2tzIHdpdGggdGhlIGVuZXJneSBvZiBhIFJlZCBFbnZlbG9wZSBSdXNoLiBJdCB0cmFuc2Zvcm1zIGV2ZXJ5IG1vbWVudCBpbnRvIGEgY2FzY2FkZSBvZiBwcm9zcGVyaXR5LCBzcHJlYWRpbmcgZm9ydHVuZSBhbmQgYWJ1bmRhbmNlIGluIHRydWUgY2VsZWJyYXRvcnkgc3R5bGUuIiwiY24iOiJJbnNwaXJlZCBieSB0aGUgc3Bpcml0IG9mIGdpdmluZywgdGhpcyBtaW5lciBwb3dlcnMgdGhyb3VnaCBibG9ja3Mgd2l0aCB0aGUgZW5lcmd5IG9mIGEgUmVkIEVudmVsb3BlIFJ1c2guIEl0IHRyYW5zZm9ybXMgZXZlcnkgbW9tZW50IGludG8gYSBjYXNjYWRlIG9mIHByb3NwZXJpdHksIHNwcmVhZGluZyBmb3J0dW5lIGFuZCBhYnVuZGFuY2UgaW4gdHJ1ZSBjZWxlYnJhdG9yeSBzdHlsZS4iLCJlcyI6Ikluc3BpcmVkIGJ5IHRoZSBzcGlyaXQgb2YgZ2l2aW5nLCB0aGlzIG1pbmVyIHBvd2VycyB0aHJvdWdoIGJsb2NrcyB3aXRoIHRoZSBlbmVyZ3kgb2YgYSBSZWQgRW52ZWxvcGUgUnVzaC4gSXQgdHJhbnNmb3JtcyBldmVyeSBtb21lbnQgaW50byBhIGNhc2NhZGUgb2YgcHJvc3Blcml0eSwgc3ByZWFkaW5nIGZvcnR1bmUgYW5kIGFidW5kYW5jZSBpbiB0cnVlIGNlbGVicmF0b3J5IHN0eWxlLiIsInB0IjoiSW5zcGlyZWQgYnkgdGhlIHNwaXJpdCBvZiBnaXZpbmcsIHRoaXMgbWluZXIgcG93ZXJzIHRocm91Z2ggYmxvY2tzIHdpdGggdGhlIGVuZXJneSBvZiBhIFJlZCBFbnZlbG9wZSBSdXNoLiBJdCB0cmFuc2Zvcm1zIGV2ZXJ5IG1vbWVudCBpbnRvIGEgY2FzY2FkZSBvZiBwcm9zcGVyaXR5LCBzcHJlYWRpbmcgZm9ydHVuZSBhbmQgYWJ1bmRhbmNlIGluIHRydWUgY2VsZWJyYXRvcnkgc3R5bGUuIn0sImNyZWF0ZWRfYnlfdGl0bGUiOnsibGluayI6IiIsInRleHQiOiIifSwibGV2ZWwiOjAsInR5cGUiOiJiYXNpYyIsImZpbGVuYW1lIjoid2VhbHRoX2dlbmVyYXRvciIsImlzX2Nhbl9iZV9zb2xkX29uX21wIjp0cnVlLCJib251cyI6Njk5LCJpc19pbl9zZXQiOmZhbHNlfX1dLCJsZXZlbHNfY29uZmlnIjpbeyJsZXZlbCI6MSwibGV2ZWxfeHAiOjIwMDAsInJlcXVpcmVkX3hwIjoyMDAwfSx7ImxldmVsIjoyLCJsZXZlbF94cCI6NzAwMCwicmVxdWlyZWRfeHAiOjkwMDB9LHsibGV2ZWwiOjMsImxldmVsX3hwIjoxMDAwMCwicmVxdWlyZWRfeHAiOjE5MDAwfSx7ImxldmVsIjo0LCJsZXZlbF94cCI6MzEwMDAsInJlcXVpcmVkX3hwIjo1MDAwMH0seyJsZXZlbCI6NSwibGV2ZWxfeHAiOjgwMDAsInJlcXVpcmVkX3hwIjo1ODAwMH0seyJsZXZlbCI6NiwibGV2ZWxfeHAiOjE5MDAwLCJyZXF1aXJlZF94cCI6NzcwMDB9LHsibGV2ZWwiOjcsImxldmVsX3hwIjoyMjAwMCwicmVxdWlyZWRfeHAiOjk5MDAwfSx7ImxldmVsIjo4LCJsZXZlbF94cCI6MTIwMDAwLCJyZXF1aXJlZF94cCI6MjE5MDAwfSx7ImxldmVsIjo5LCJsZXZlbF94cCI6MzYwMDAsInJlcXVpcmVkX3hwIjoyNTUwMDB9LHsibGV2ZWwiOjEwLCJsZXZlbF94cCI6MTgwMDAwLCJyZXF1aXJlZF94cCI6NDM1MDAwfSx7ImxldmVsIjoxMSwibGV2ZWxfeHAiOjMwMDAwMCwicmVxdWlyZWRfeHAiOjczNTAwMH0seyJsZXZlbCI6MTIsImxldmVsX3hwIjo2MjAwMDAsInJlcXVpcmVkX3hwIjoxMzU1MDAwfSx7ImxldmVsIjoxMywibGV2ZWxfeHAiOjE1MDAwMCwicmVxdWlyZWRfeHAiOjE1MDUwMDB9LHsibGV2ZWwiOjE0LCJsZXZlbF94cCI6MzgwMDAwLCJyZXF1aXJlZF94cCI6MTg4NTAwMH0seyJsZXZlbCI6MTUsImxldmVsX3hwIjo0MTAwMDAsInJlcXVpcmVkX3hwIjoyMjk1MDAwfSx7ImxldmVsIjoxNiwibGV2ZWxfeHAiOjgzMDAwMCwicmVxdWlyZWRfeHAiOjMxMjUwMDB9LHsibGV2ZWwiOjE3LCJsZXZlbF94cCI6NDUwMDAwLCJyZXF1aXJlZF94cCI6MzU3NTAwMH0seyJsZXZlbCI6MTgsImxldmVsX3hwIjo1NTAwMDAsInJlcXVpcmVkX3hwIjo0MTI1MDAwfSx7ImxldmVsIjoxOSwibGV2ZWxfeHAiOjE1MDAwMDAsInJlcXVpcmVkX3hwIjo1NjI1MDAwfSx7ImxldmVsIjoyMCwibGV2ZWxfeHAiOjUwMDAwMDAsInJlcXVpcmVkX3hwIjoxMDYyNTAwMH1dfQ==";

// Função para converter valor em GHs, THs ou PHs com base no valor
function formatPower(value) {
    if (value >= 1e6) {
        // Base 9: PHs (Petahashes)
        return `${(value / 1e6).toFixed(2)} PHs`;
    } else if (value >= 1e3) {
        // Base 6: THs (Terahashes)
        return `${(value / 1e3).toFixed(2)} THs`;
    } else {
        // Valores menores que 1000
        return `${(value)} GHs`; // Supondo que para valores menores que 1000 a unidade seja Hashes
    }
}

// Função para decodificar a string BASE64
//function base64Decode(str) {
    //const decodedString = base64DecodeLarge(base64String);
    //const decoded = atob(str);
    //return decodeURIComponent(escape(decoded));
//}

// Decodifica a string BASE64 
const decodedString = base64DecodeLarge(base64String);
const jsonData = JSON.parse(decodedString);

// Extrai informações do JSON
const eventDescription = jsonData.event.title.en;
const rewards = jsonData.rewards;
const levelsConfig = jsonData.levels_config || [];

// Inicializa o total acumulado de XP
let totalXP = 0;
let totalPower = 0;
let totalBonus = 0;
let totalCustomValue = 0;

// Cria um mapa de níveis para XP
const levelXPMap = levelsConfig.reduce((acc, level) => {
    acc[level.level] = level.level_xp;
    return acc;
}, {});

// Função para converter nível em nome
function levelToName(level) {
    switch (level) {
        case 0: return "COMUM";
        case 1: return "INCOMUM";
        case 2: return "RARA";
        case 3: return "ÉPICA";
        case 4: return "LENDÁRIA";
        case 5: return "UNREAL";
        default: return "Desconhecido";
    }
}

// Função para atualizar os totais
function updateTotals() {
    totalBonus = 0;
    totalCustomValue = 0;

    // Itera sobre as linhas da tabela para somar os valores
    tableBody.querySelectorAll('tr').forEach(row => {
        let powerCell = row.children[4]; // Coluna 5 (Power)
        let bonusCell = row.children[5]; // Coluna 6 (Bonus)
        let customValueCell = row.children[7]; // Coluna 8 (Valores Personalizados)

        // Atualiza o total de Power
        if (powerCell) {
            let powerText = powerCell.textContent;
            // Extrai o número antes da unidade de formatação
            let powerValue = parseFloat(powerText);
            if (!isNaN(powerValue)) {
                totalPower += powerValue;
            }
        }

        // Atualiza o total de Bonus
        if (bonusCell && bonusCell.textContent.endsWith('%')) {
            let bonusValue = parseFloat(bonusCell.textContent);
            if (!isNaN(bonusValue)) {
                totalBonus += bonusValue;
            }
        }

        // Atualiza o total de Valores Personalizados
        let inputValue = customValueCell.querySelector('input');
        if (inputValue) {
            let inputValueNumber = parseFloat(inputValue.value) || 0;
            totalCustomValue += inputValueNumber;
        }
    });

    // Atualiza a linha de totais
    let totalRow = tableBody.querySelector('tr.total-row');
    if (totalRow) {
        // Atualiza a célula de Power
        totalRow.children[4].innerHTML = `Total Power<br>${formatPower(totalPower)}`;

        // Atualiza a célula de Bonus
        totalRow.children[5].innerHTML = `Total Bonus<br>${(totalBonus).toFixed(2)} %`;

        // Atualiza a célula de Valores Personalizados
        totalRow.children[7].innerHTML = `Valor Total<br>${totalCustomValue.toFixed(2)}`;
    }
}

// Função para adicionar a linha de totais
function addTotalsRow() {
    let row = document.createElement('tr');
    row.className = 'total-row';

    // Cria a célula para cada coluna, inicialmente vazia ou com rótulo
    for (let i = 0; i < 8; i++) {
        let cell = document.createElement('td');
        if (i === 4) { // Power
            cell.innerHTML = `Total Power<br>${formatPower(totalPower)}`;
        } else if (i === 5) { // Bonus
            cell.innerHTML = `Total Bonus<br>${(totalBonus).toFixed(2)} %`;
        } else if (i === 7) { // Custom Value
            cell.innerHTML = `Valor Total<br>${totalCustomValue.toFixed(2)}`;
        } else {
            cell.style.backgroundColor = '#ddd'; // Define o fundo da célula como cinza
            cell.textContent = ''; // Deixa o conteúdo da célula vazio
        }
        row.appendChild(cell);
    }

    tableBody.appendChild(row);
}

// Preenche o cabeçalho da tabela com o título do evento
const tableHeaderRow = document.querySelector('#nomeevento');
const headerCell = document.createElement('th');
headerCell.colSpan = 8; // Como há 8 colunas, faz sentido usar colSpan=8
headerCell.textContent = eventDescription;
tableHeaderRow.appendChild(headerCell);

// Preenche a tabela com os dados
const tableBody = document.querySelector('#dataTable tbody');

rewards.forEach(reward => {
    let row = document.createElement('tr');

    // Cria a célula para o nível
    let cellLevel = document.createElement('td');
    cellLevel.textContent = reward.required_level || '-';
    row.appendChild(cellLevel);
    
    // Calcula e atualiza o XP total
    let cellXPValue = levelXPMap[reward.required_level] || 0;
    totalXP += parseFloat(cellXPValue);

    let cellXP = document.createElement('td');
    cellXP.textContent = cellXPValue.toLocaleString() || '-';
    row.appendChild(cellXP);

    let cellTotalXP = document.createElement('td');
    cellTotalXP.textContent = Math.floor(totalXP).toLocaleString();
    row.appendChild(cellTotalXP);

    // Cria a célula para a quantidade e imagem
    let cellAmount = document.createElement('td');

    if (reward.type === 'money') {
        // Cria uma <div> para a imagem e a outra <div> para o texto
        let imageContainer = document.createElement('div');
        let textContainer = document.createElement('div');

        // Define a imagem fixa baseada na moeda
        let currencyImageURL = reward.currency === 'RLT'
            ? 'https://rollercoin.com/static/img/seasonPass/reward_RLT.png'
            : 'https://rollercoin.com/static/img/seasonPass/reward_RST.png';

        // Cria a imagem para a moeda
        let currencyImage = document.createElement('img');
        currencyImage.src = currencyImageURL;
        currencyImage.alt = reward.currency;
        currencyImage.style.width = '50px'; // Define o tamanho da imagem
        currencyImage.style.height = 'auto'; // Mantém a proporção da altura

        // Adiciona a imagem ao container da imagem
        imageContainer.appendChild(currencyImage);

        // Adiciona o container da imagem e o texto à célula
        cellAmount.appendChild(imageContainer);

        // Cria o texto para a quantidade
        let amountText = document.createElement('span');
        amountText.textContent = ` ${(reward.amount / 1000000).toFixed(2)} ${reward.currency}`;

        // Adiciona o texto ao container do texto
        textContainer.appendChild(amountText);

        // Adiciona o container do texto à célula
        cellAmount.appendChild(textContainer);
    } else if (reward.type === 'miner') {
        const item = reward.item || {};
        
        // Cria uma <div> para a imagem e a outra <div> para o texto
        let imageContainer = document.createElement('div');
        let textContainer = document.createElement('div');

        // Construa a URL da imagem do minerador
        const baseURL = "https://static.rollercoin.com/static/img/market/miners/";
        const filename = item.filename;
        const imageURL = `${baseURL}${filename}.gif`;

        // Cria o link para o minerador
        let minerLink = document.createElement('a');
        minerLink.href = `https://rollercoin.com/marketplace/buy/miner/${item._id}`;
        minerLink.target = "_blank"; // Abre em nova aba

        // Cria a imagem para o minerador
        let minerImage = document.createElement('img');
        minerImage.src = imageURL;
        minerImage.alt = item.name.en;
        minerImage.style.width = '50px'; // Define o tamanho da imagem
        minerImage.style.height = 'auto'; // Mantém a proporção da altura

        // Adiciona a imagem ao link
        minerLink.appendChild(minerImage);
        
        // Adiciona o link ao container da imagem
        imageContainer.appendChild(minerLink);

        // Cria o texto para o nível e nome do item
        let itemDetails = document.createElement('span');
        let levelName = levelToName(item.level); // Converte o nível para nome

        // Adiciona o nível em negrito e aplica a cor correta baseado no nome
        let levelSpan = document.createElement('span');
        levelSpan.style.fontWeight = 'bold'; // Aplica o negrito
        switch (levelName) {
            case "INCOMUM":
                levelSpan.style.color = '#2bff00'; // Verde para INCOMUM
                break;
            case "RARA":
                levelSpan.style.color = '#00eaff'; // Azul para RARA
                break;
            case "ÉPICA":
                levelSpan.style.color = '#ff00bb'; // Rosa para ÉPICA
                break;
            case "LENDÁRIA":
                levelSpan.style.color = '#fffb00'; // Amarelo para LENDÁRIA
                break;
            case "UNREAL":
                levelSpan.style.color = '#ff0000'; // Vermelho para UNREAL
                break;
            default:
                levelSpan.style.color = ''; // Mantém a cor padrão para COMUM ou desconhecido
        }

        // Define o texto com o nível
        levelSpan.textContent = ` ${levelName}`;

        // Adiciona o nome do item e o nível ao container de texto
        itemDetails.textContent = item.name?.en;
        itemDetails.appendChild(levelSpan);

        // Adiciona o texto ao container de texto
        textContainer.appendChild(itemDetails);

        // Adiciona os containers à célula
        cellAmount.appendChild(imageContainer);
        cellAmount.appendChild(textContainer);
    } else if (reward.type === 'power') {
        // Cria uma <div> para a imagem e a outra <div> para o texto
        let imageContainer = document.createElement('div');
        let textContainer = document.createElement('div');

        // Define a URL da imagem do poder temporário
        const powerImageURL = 'https://rollercoin.com/static/img/seasonPass/reward_power.png';

        // Cria a imagem para o poder temporário
        let powerImage = document.createElement('img');
        powerImage.src = powerImageURL;
        powerImage.alt = 'Power';
        powerImage.style.width = '50px'; // Define o tamanho da imagem
        powerImage.style.height = 'auto'; // Mantém a proporção da altura

        // Adiciona a imagem ao container da imagem
        imageContainer.appendChild(powerImage);

        // Formata o valor do poder
        let formattedPower = (reward.amount / 1000000).toFixed(2);

        // Cria o texto para a quantidade de poder
        let powerText = document.createElement('span');
        powerText.textContent = `${formattedPower} PHs Temporário`;

        // Adiciona o texto ao container de texto
        textContainer.appendChild(powerText);

        // Adiciona os containers à célula
        cellAmount.appendChild(imageContainer);
        cellAmount.appendChild(textContainer);
    } else if (reward.type === 'rack') {
        const item = reward.item || {};

        // Cria uma <div> para a imagem e a outra <div> para o texto
        let imageContainer = document.createElement('div');
        let textContainer = document.createElement('div');

        // Construa a URL da imagem do rack
        const baseURL = "https://static.rollercoin.com/static/img/market/racks/";
        const filename = item._id;
        const imageURL = `${baseURL}${filename}.png`;

        // Cria o link para o rack
        let rackLink = document.createElement('a');
        rackLink.href = `https://rollercoin.com/marketplace/buy/rack/${item._id}`;
        rackLink.target = "_blank"; // Abre em nova aba

        // Cria a imagem para o rack
        let rackImage = document.createElement('img');
        rackImage.src = imageURL;
        rackImage.alt = item.name.en;
        rackImage.style.width = '50px'; // Define o tamanho da imagem
        rackImage.style.height = 'auto'; // Mantém a proporção da altura

        // Adiciona a imagem ao link
        rackLink.appendChild(rackImage);
        
        // Adiciona o link ao container da imagem
        imageContainer.appendChild(rackLink);

        // Cria o texto para o nome do item
        let itemDetails = document.createElement('span');
        itemDetails.textContent = `${item.name?.en}`;

        // Adiciona o texto ao container de texto
        textContainer.appendChild(itemDetails);

        // Adiciona os containers à célula
        cellAmount.appendChild(imageContainer);
        cellAmount.appendChild(textContainer);
    } else if (reward.type === 'season_pass_xp') {
    // Cria uma <div> para a imagem e a outra <div> para o texto
    let imageContainer = document.createElement('div');
    let textContainer = document.createElement('div');

    // URL da imagem XP
    const xpImageURL = 'https://minaryganar.com/wp-content/uploads/2024/03/EXP.png';

    // Cria a imagem para XP
    let xpImage = document.createElement('img');
    xpImage.src = xpImageURL;
    xpImage.alt = 'XP';
    xpImage.style.width = '50px'; // Define o tamanho da imagem
    xpImage.style.height = 'auto'; // Mantém a proporção da altura

    // Adiciona a imagem ao container da imagem
    imageContainer.appendChild(xpImage);

    // Cria o texto para a quantidade de XP
    let amountText = document.createElement('span');
    amountText.textContent = ` ${reward.amount} XP`; // Exibe o amount seguido de XP

    // Adiciona o texto ao container de texto
    textContainer.appendChild(amountText);

    // Adiciona os containers à célula
    cellAmount.appendChild(imageContainer);
    cellAmount.appendChild(textContainer);
} else {
    cellAmount.textContent = '-';
}

    row.appendChild(cellAmount);

    let cellPower = document.createElement('td');
    let rawPowerValue = reward.item?.power || 0;
    if (rawPowerValue) {
        totalPower += rawPowerValue;
    }
    cellPower.textContent = reward.item?.power ? formatPower(reward.item.power) : '-';
    row.appendChild(cellPower);

    let cellBonus = document.createElement('td');
    const bonus = reward.item?.bonus != null ? (reward.item?.bonus / 100).toFixed(2) : '-';
    cellBonus.textContent = bonus !== '-' ? `${bonus} %` : '-';
    row.appendChild(cellBonus);

    let cellCanBeSoldOnMP = document.createElement('td');
    if (reward.type === 'rack') {
        // Se o tipo for 'rack', o conteúdo será sempre vazio (resultando em true)
        cellCanBeSoldOnMP.textContent = '';
    } else {
        // Caso contrário, mantém a lógica original
        cellCanBeSoldOnMP.textContent = reward.item?.is_can_be_sold_on_mp ? '' : 'X';
    }
    row.appendChild(cellCanBeSoldOnMP);

    // Nova célula para o valor personalizado, editável pelo usuário
    let cellCustomValue = document.createElement('td');
    let input = document.createElement('input');
    input.type = 'number';  // Define o tipo como numérico
    input.name = 'cellValor';  // Nome para identificação do input
    input.value = '';  // Valor padrão

    input.className = 'input-custom'; // Adiciona a classe personalizada
    cellCustomValue.appendChild(input);
    row.appendChild(cellCustomValue);

    tableBody.appendChild(row);
});

// Adiciona a linha de totais
addTotalsRow();

// Atualiza os totais inicialmente
updateTotals();

// Adiciona um evento de mudança a cada input da coluna 8
tableBody.addEventListener('input', event => {
    if (event.target.tagName === 'INPUT') {
        updateTotals();
    }
});

// Define o título da página
document.title = `RKFox - ${eventDescription}`;

// Adiciona funcionalidade de modo escuro
document.getElementById('toggle-dark-mode').addEventListener('change', (event) => {
    if (event.target.checked) {
        document.body.classList.add('dark-mode');
    } else {
        document.body.classList.remove('dark-mode');
    }
});
